sudo: required
services:
  - docker

before_install:
  - docker build -t shaelraj/docker-react -f Dockerfile.dev .

script:
  - docker run shaelraj/docker-react npm run test -- --coverage

#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-30647662547"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESSS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
